### Get All Products
GET http://localhost:3000/products

### Create Product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "guard",
    "price": 100
}

### Create Product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "y",
    "price": 100
}